config/routes.rb
Rails.application.routes.draw do
  resources :events

  root 'events#index'

end

app/models/bookstore.rb
class Bookstore < ActiveRecord::Base
  validates_presence_of :name
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
before_action :dofirst, :only => [ :update, :edit, :destroy]
  def index
    @events = Event.page(params[:page]).per(5)
    @e_new = Event.new
  end


  def create
    @event=Event.new( event_params )
    if @event.save
      flash[:n] = "新增成功"
      redirect_to events_url
    else
      render :action => :new
    end
  end

  def show
    index
    @e_show=Event.find(params[:id])
    render :action => :index
  end

  def edit
    index
    render :action => :index
  end

  def update
    if @event.update(event_params)
      flash[:n] = "修改成功"
      redirect_to events_url
    else
      render :action => :edit
    end
  end

  def destroy
    @event.destroy
    flash[:alert] = "刪除成功"
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :isbn, :description, :soldtime, :builddate)
  end

  def dofirst
    @event=Event.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


  def user_photo(user)
    image_tag( user.photo, :width => "150", :class => "user photo" )
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_input.erb
<table class="table">
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>
  <p></p>
  <%= f.label :isbn, "ISBN" %>
  <%= f.text_field :isbn %>
  <p></p>
  <%= f.label :description, "Description" %>
  <%= f.text_field :description %>
  <p></p>
  <%= f.label :builddate, "Build Date" %>
  <%= f.date_select :builddate %>
  <p></p>
  <%= f.label :soldtime, "Sold Time" %>
  <%= f.datetime_select :soldtime %>
  <p></p>
</table>


  <% if @event!=nil %>

  <% if @event.errors.any? %>
  <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
  <% end %>
  <% end %>

app/views/events/index.html.erb
<h1>Index</h1>

<% @events.each do |f| %>

  <table class="table table-hover">
    <tr>
      <td class="col-md-9"><%= f.name %></td>
      <td class="col-md-1"><button class="btn btn-default" type="submit"><%= link_to '顯示',event_path(f) %></button></td>
      <td class="col-md-1"><button type="button" class="btn btn-success"><%= link_to '修改',edit_event_path(f) %></button></td>
      <td class="col-md-1"><button type="button" class="btn btn-danger"><%= link_to '刪除',event_path(f) , :method => :delete %></button></td>
    </tr>
  </table>

<% end %>
  <%= paginate @events %>

<% if @e_show %>
<h1 class="col-md-12"> ===== SHOW =====</h1>
  <table class="table">
    <tr>
      <td class="col-md-2">id: <%= @e_show.id %></td>
      <td class="col-md-2">Name: <%= @e_show.name %></td>
      <td class="col-md-2">ISBN: <%= @e_show.isbn %></td>
      <td class="col-md-2">Des: <%= @e_show.description %></td>
      <td class="col-md-2">Build Date: <%= @e_show.builddate %></td>
      <td class="col-md-2">Sold Time: <%= @e_show.soldtime %></td>
    </tr>
  </table>

<% end %>


<% if @event %>
  <h1> ===== EDIT =====</h1>

  <%= form_for @event, url: event_path(@event), :method => :patch do |f| %>
    <%= render :partial => "input", :locals => { :f => f } %>
    <%= f.submit "update" %>
  <% end %>
<% end %>


<h1> ===== NEW =====</h1>

<%= form_for @e_new, url: events_path do |f| %>
  <%= render :partial => "input", :locals => { :f => f } %>
  <%= f.submit "input" %>
<% end %>

app/views/events/show.html.erb
<h1>SHOW</h1>
<p>id: <%= @event.id %></p>
<p>Name: <%= @event.name %></p>
<p>ISBN: <%= @event.isbn %></p>
<p>Des: <%= @event.description %></p>
<p>Build Date: <%= @event.builddate %></p>
<p>Sold Time: <%= @event.soldtime %></p>


<p><%= link_to '回首頁', events_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sky' Book HomeWord</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p style="color: green"><%= flash[:n] %></p>
<p style="color: red"><%= flash[:alert] %></p>

<%= yield %>

</body>
</html>